### ISSUE TITLE
quickly changing rooms causes background layers to disappear

### ISSUE THREAD

**Issue by Starlash** [omicronrex/renex-engine#33]
ive known this bug for a while, possibly related to BackgroundDaemon not being created/despawning and such

to reproduce:
- press pageup/pagedown on rooms with multiple background layers (sometimes it can also cut out backgrounds from rooms with only 1 background)
- very rarely occurs when going just from one room to the next, also almost never occurs if the rooms load very fast (had this happen with regular warp objects, but only once in a blue moon)
- occurs every time if you press pageup/pagedown twice in very quick succession and the rooms take multiple frames to load (switching rooms _while_ the previous one is loading?)
- mainly occurs if the room you're going to after pressing pageup/pagedown twice has the same background layers as the room that got 'skipped'

**Comment by omicronrex** [comment]
attempted fix in 07de8cfbdcbcdd3cd081a23dcc6f54b4ccc8c53d

**Comment by omicronrex** [comment]
can't reproduce in latest
