### ISSUE TITLE
first time saving causes a weird screenshot in fullscreen mode

### ISSUE THREAD

**Issue by Starlash** [omicronrex/renex-engine#36]
the first time you save on a save, a weird distorted screenshot appears in the top left of the screen
only happens in fullscreen mode, doesnt happen with windowed (nor windowed + zoom)
i suspect it's related to both the savefile thumbnail and the idolmaster save, since this doesn't happen when EITHER of them are off

**Comment by Starlash** [comment]
update: this doesn't necessarily happen on the first time you save on a save
rather, when you open up the game, every save you haven't saved at before (while the game was open) causes this

**Comment by omicronrex** [comment]
any settings required to reproduce this? only thing that happens in my testing is 1 frame of gui events is skipped.

**Comment by Starlash** [comment]
not that i know of, this happened when testing both with the save folder intact and without it entirely

**Comment by omicronrex** [comment]
fixed by 66c6551665c49c28186bb157861faba3dfd0c5fe
