### ISSUE TITLE
onPlatform is probably meant to be onGround for mario mode physics in movement step

### ISSUE THREAD

**Issue by nataliexists** [omicronrex/renex-engine#37]
im working on a fangame with boosters that boost the players hspeed (think of stuff like celestes bumpers and lines from flywrench) and the mario physics worked differently on platforms than on regular blocks, even before i added the gimmick

pretty sure it isnt meant to be like this

**Comment by omicronrex** [comment]
fixed in 3e0994667a96f2c2fdca312a33efe59813cb6726
